use_frameworks!

platform :ios, '9.0'

target 'LocalNotificationsService_Example' do
  pod 'LocalNotificationsService', :path => '../'

  target 'LocalNotificationsService_Tests' do
    inherit! :search_paths

    
  end
end
